version: '3'

services:
  web: 
    build: .
    ports: 
      - '5000:5000'
  py-web:
    build: py-web/
    ports:
      - '8000:8000'
    depends_on:
      - web 
  zap2docker:
    image: owasp/zap2docker-weekly
    ports:
      - "8080:8080"
    environment:
      LEVEL_TO_SHOW: PASS
      REPORT_FILE: api_report.json
      TARGET: http://py-web:8000/openapi.json
    depends_on:
      - py-web 
    volumes:
      - ./:/zap/wrk
      - ./zap-api-scan.sh:/zap/wrk/zap-api-scan.sh
    entrypoint: /zap/wrk/zap-api-scan.sh
