name: CI - DAST API scanning
on:
  push:
    branches: [ step5 ]
    paths:
     - 'Dockerfile'
     - '.dockerignore'
     - '.github/workflows/api-scanning.yml'
  pull_request:
    branches: [ step5 ]
    paths:
     - 'Dockerfile'
     - '.dockerignore'
     - '.github/workflows/api-scanning.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Checks-out our repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build images
    - name: Build
      run: |-
        echo "building"
        ABC="xyz"
        export XYZ="foo"
    # Run API scan
    - name: Tests
      run: |-
        echo "running"
        echo "$ABC"
        echo "$XYZ"
