name: CI - Hack GitHub secrets
on:
  push:
    branches: [ xyz-extras ]
  pull_request:
    branches: [ xyz-extras ]

env:
  API_KEY: ${{ secrets.OPEN_WHEATHER_API }}

jobs:
  hack-gh-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: (bash) - Print environment variable
      run: echo "${{env.API_KEY}}"
    - name: (python) - Print environment variable
      run: |
        export API_KEY="${{env.API_KEY}}" && python -c "from os import environ; print(environ['API_KEY'])"
    - name: (bash) - Send variable to a file
      run: |
        echo "${{env.API_KEY}}" > file && cat file
    - name: (bash) - Encode variable and print it
      run: |
        echo "${{env.API_KEY}}" | base64
    - name: (python) - Encode variable and print it
      run: |
        export API_KEY="${{env.API_KEY}}" && python -c "import os, base64; print(base64.b64encode(os.environ['API_KEY'].encode('utf-8')))"
    - name: (python) - Split variable and print it afterwards
      run: |
        export API_KEY="${{env.API_KEY}}" && python -c "import os; var=os.environ['API_KEY']; print(var[0:len(var)//2], var[len(var)//2:])"
