name: CI - Hack GitHub secrets
on:
  push:
    branches: [ xyz-extras ]
  pull_request:
    branches: [ xyz-extras ]

env:
  API_KEY: ${{ secrets.OPEN_WHEATHER_API }}

jobs:
  hack-gh-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: (bash) - Print environment variable
      run: echo "${{env.API_KEY}}"
    - name: (python) - Print environment variable
      run: |
        export API_KEY="${{env.API_KEY}}" && python -c "from os import environ; print(environ['API_KEY'])"
    - name: (bash) - Send variable to a file
      run: |
        echo "${{env.API_KEY}}" > file && cat file
    - name: (bash) - Encode variable and print it
      run: |
        DUMMY_VAR=$(echo "${{env.API_KEY}}" | base64) && echo $DUMMY_VAR
    - name: (python) - Encode variable and print it
      run: |
        export API_KEY="${{env.API_KEY}}" && python -c "import os, base64; dummy=base64.b64encode(os.environ['API_KEY'].encode('ascii')); print(dummy)"

