name: CI - Renovate
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  workflow_call:  # Triggered manually from another workflow
  schedule:
    - cron: '0 9 * * 0'  # Scheduled to run every Sunday at 9:00 AM

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          renovate-version: full
          token: ${{ secrets.GITHUB_TOKEN }}
