name: CI - step1
on:
  push:
    branches:
      - step1
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  step1:
    name: Step1
    runs-on: ubuntu-latest
    needs: [setup, start]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Moving to step1
        run: git checkout step1
      - name: Add a line with config.ini in gitignore
        run: |
          sed -i -- 's/#config.ini/config.ini/g' .gitignore
          #echo config.ini >> .gitignore
      - name: Add gitignore to the repo
        run: |
          git add .gitignore
          git commit -m "ignore config.ini file"
      - name: Create and fill out config.ini file locally
        run: cp -v samples/config.ini.sample config.ini
      - name: Ensure that the private config.ini is ignored
        run: |
          grep -r --color config.ini .gitignore | grep -v "#"
          git check-ignore -v config.ini
